language: python
python: '2.7'
sudo: required
addons:
  apt:
    update: true
services:
    - docker
jobs:
  include:
  - stage: test
    env: Type='mock build test'
    before_install:
    - docker pull centos:centos7
    script:
    - ./include/travis/run_in_centos7_docker.sh include/travis/mock_build_test.sh
  - stage: deploy-pypi
    if: branch =~ ^v\d+\.\d+\.\d+-1.*$
    env: Type='PyPi deploy'
    script: skip
    deploy:
      provider: pypi
      user: iml
      password:
        secure: ft/srevwOsZ/bRtmyqtv2MJVggjvIfNp7Yf402qdD+tCVzBEWLd3YplHgW0kziI26H4ElR/cTdL0KoLPe0s8SVGb1BZ9GyqG0qjgkotxVwyy4LzlHKwsCuEYSJbOLUbzpcvzcjpEU9PwY+AKeA3DiJsbC7FTrve7fmeS9NZ1+X3tEZL/mmszHUXwo17onHx1057UkOlizLEMwz/cuUnS0klSogF4M/u3PTVxIUdrrG3dDzf4vKPXPLtnxq+vKuysP0YAGDo0podsb7ZZLyV7X6tsRfMkwJJhnYPayr25QLAyWbFjS7hWCpHJ0OQ2S+4bjJFL/3WfBQykRqg423jfI4qjUTgK238VuviY0BGcTLttISLLAufpZVu7UcP26g6WqvPhXog1NIOHFNuZgvG0mwOJhKKwr6k/BEoky/0Ijj3cDW4jyjqj8I9FAm3z7tgnfiYT3eQlIanjxkGVqBKRmDah7GGjG/YNO441zrga9sPJ6LdXfwrX+1qW9OzGDHAMT7LhoGMLz1qPv1ns+STsDRLAn1vkwReawaj4Se1dzwTzm5v3xsQx3dGKqZ3rBlH6UWl7r44VAZ6Z/haLBrXGHvoPFNEdH0L8YnM8eWGBmuvqjnmiAcHK5+FgAQYcjgxZd8efrIJOOG3xMroT7weZbeTTnSGP29Tm0VZL7V12tWc=
      on:
        all_branches: true
        distributions: sdist bdist_wheel
  - stage: deploy-copr
    if: branch =~ ^v\d+\.\d+\.\d+-.+$
    env: Type='Copr deploy'
    script: skip
    before_deploy:
    - include/travis/copr-deploy.sh prepare
    deploy:
      skip_cleanup: true
      provider: script
      script: ./travis_wait "./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh build"
      on:
        all_branches: true
