language: python
python: '2.7'
script: echo "no tests"
deploy:
  provider: pypi
  user: iml
  password:
    secure: BYl08q7WVXAJMJmV2LR07wC6KJUaUAlSugbNo+hrmFtgLVe55Gqq/ay2vJcCr9dxuR8yo5Y2bSZYbFOTmW3WcCD9QtwoiyF8WlYMEU2qlQcTaAOjoYIB3HlvMqAH4cYSdvuoAI7C2s6hI22tDP/Nyvr91xheBaQ+EC5j8gGm14aPJvB3V4nCg09uIkbJw07KVHMODLjcSaIptpJLKaNmWrrOff9Wg+0KT0An0tt4JV2K/tSogNPZHSUfYFw1DmEt7xQGtqUY/grKDVAZLPGfSfT+LzA4GEB48MDyHiVo9xDCgIFZ2ymeyI4sqBaIB1Bz83KFThbsCfnMbcGDGRn055FDq0JKYJ4N2x+bPsJRpg8S/XZI1yEFvkfGzUI8rtZIJIDqR9jqUUJ2txzcDwtGEYPR6QrkY8xoJYCGhKZJGfWw+Y64j4a4Nlf9th6ld3dYmmCjSvX0cZql8VW6S9GCeE1g9IJcrzjFwU2DfFTlVRaVRkRQZIQMZsgV354j4aQNpuexhOWINbxpdFtaHdizefdkdiAAnr/rOM/I8b8K7l4Pg1kLlA5HUu95iw3hPxZFWUWmDzJ3RRy2RIw033zwY8YlixifHCPebD2xilwk2ef0Y97H5TdVXPcl6cbZx5nVzzDVgTxNMlyCUbbAc0FoeXKnOipu7t0EnelvPDJvi0s=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: intel-hpdd/iml_sos_plugin
