name: prod-release
on:
  push:
    tags:
      - v*-r6.2
  push_python_iml:
    name: Push to Copr prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Push rpm
        uses: ./.github/actions/copr
        env:
          PROD: true
          OWNER: managerforlustre
          PROJECT: manager-for-lustre-6.2
          PACKAGE: python-iml_sos_plugin
          SPEC: python-iml_sos_plugin.spec
          SRPM_TASK: srpm
          WORKSPACE: ${{ github.workspace }}
          KEY: ${{ secrets.key }}
          IV: ${{ secrets.iv }}
